### ISSUE TITLE
Can not generate xz file while using spark

### ISSUE THREAD

**Issue by yanzt** [yongtang/hadoop-xz#3] opened 2015-06-07 02:26 UTC
Hi,
I tried using it with Spark to generate xz compressed file but can not make it work. The following is my code:
object GztoXZ {
  def main(args: Array[String]) {

```
if (args.length < 2) {
  System.err.println("Usage: GztoXZ gzfile xzfile")
  System.exit(1)
}
val conf = new SparkConf().setAppName("Gzip transform to xz")
conf.set("io.compression.codecs","io.sensesecure.hadoop.xz.XZCodec")
val spark = new SparkContext(conf)
println("Start spark task!")

val inPath = args(0)
val outPath = args(1)

val content = spark.textFile(inPath)


content.map(line=>{
      line
    }).coalesce(1,true).saveAsTextFile(outPath,classOf[io.sensesecure.hadoop.xz.XZCodec])

spark.stop()
```

  }
}

It always generate empty result. Is there anything I missed?

**Comment by yongtang** [comment] 2015-06-20 20:40
Sorry for the late reply. I tried your test program with Spark 1.3.1 (spark-1.3.1-bin-hadoop2.6.tgz) and didn't find any issues. The part-00000.xz is created as expected. Could the issue you encounter is related to Hadoop and Spark version? --- yongtang

Below is the build.sbt I use:

``` scala
name := "GztoXZ"

version := "1.0"

scalaVersion := "2.10.4"

javacOptions ++= Seq("-source", "1.7", "-target", "1.7")

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.3.1"
libraryDependencies += "io.sensesecure" % "hadoop-xz" % "1.4"
```

**Comment by yongtang** [comment] 2015-07-06 00:19
Close the issue as unable to reproduce. Please reopen if necessary.

**Closed as completed by yongtang** 2015-07-06 00:19 UTC
